//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EighthDay.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.Buy = new HashSet<Buy>();
            this.GoodsStock = new HashSet<GoodsStock>();
            this.Sell = new HashSet<Sell>();
        }
    
        public double ID { get; set; }
        public string Name { get; set; }
        public string International { get; set; }
        public System.DateTime Begin { get; set; }
        public System.DateTime End { get; set; }
        public bool Yes { get; set; }
        public string RF { get; set; }
        public string Producer { get; set; }
        public string Instructions { get; set; }
        public int BatchID { get; set; }
        public decimal Price { get; set; }
    
        public virtual Batches Batches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buy> Buy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsStock> GoodsStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sell> Sell { get; set; }
    }
}
