//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EighthDay.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entity : DbContext
    {
        public Entity()
            : base("name=Entity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Batches> Batches { get; set; }
        public virtual DbSet<Buy> Buy { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<GoodsStock> GoodsStock { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Sell> Sell { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
