//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EighthDay.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell
    {
        public int ID { get; set; }
        public double GoodsID { get; set; }
        public int ClientID { get; set; }
        public short CountNumber { get; set; }
        public System.DateTime DateStarts { get; set; }
        public double Count { get; set; }
        public decimal Markup { get; set; }
        public decimal Sum { get; set; }
        public bool Cash { get; set; }
        public string Worker { get; set; }
        public short Invoice { get; set; }
        public string Seller { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Goods Goods { get; set; }
    }
}
